services:
  nginx:
    container_name: nextcloud-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nextcloud_data:/var/www/html:ro
    depends_on:
      - nextcloud
    networks:
      - nextcloud

  db:
    container_name: nextcloud-db
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud_secure_2024
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nextcloud

  redis:
    container_name: nextcloud-redis
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - nextcloud

  nextcloud:
    container_name: nextcloud
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud_secure_2024
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=768M
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=ChangeMe2024!
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.local localhost 127.0.0.1
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.local
      - OVERWRITECLIURL=https://nextcloud.local
    volumes:
      - nextcloud_data:/var/www/html
    extra_hosts:
      - "nextcloud.local:172.18.0.5"
    networks:
      - nextcloud

  documentserver:
    container_name: nextcloud-onlyoffice
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    depends_on:
      - nextcloud
    ports:
      - "8081:80"
    environment:
      - TZ=Europe/Paris
      - JWT_ENABLED=true
      - JWT_SECRET=super-secret-jwt-2024-change-me
      - JWT_HEADER=Authorization
      - USE_UNAUTHORIZED_STORAGE=true    # refus des URLs avec certificats SSL auto-signés /  URLs en HTTP non chiffré  /  Sources non vérifiées
    extra_hosts:
      - "nextcloud.local:172.18.0.5"
    networks:
      - nextcloud

volumes:
  db_data:
  redis_data:
  nextcloud_data:

networks:
  nextcloud:
    driver: bridge